name: sample action
on: push
jobs:
  remote-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Use remote action
        uses: weboltreongithub/test1@v2.0
        with:
            who-to-greet: 'Ciao'
