name: C/C++ CI

on:
  push:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest

      steps:

      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      
      - name: configure
        run: ./configure
      
      - name: make
        run: make

      - name: App execution
        run: |
            output=$(./hello)
            if [ "${output}" != "Hello, World!" ]; then
                echo "Error in app response"
                exit 1
            fi